### ISSUE TITLE
postprocessor does not work in FreeCAD 0.20.1 - generates error

### ISSUE THREAD

**Issue by spitzlbergerj** [Snapmaker/snapmaker_cnc_post_process#23]
Hi,

I use this FreeCAD version
```
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * LCInterlocking
```

With some of the other preprocessors I was able to generate the gcode successfully (marlin, linuxcnc, centroid).

After the error occurred with the snapmaker preprosseor of this repository for the first time, I tried to adapt the imports to the other preprocessors:

```
# sjj, 2023-01-02, begin
# Changed because of an error while postprocessiong
# see https://forum.freecadweb.org/viewtopic.php?p=640402#p640402
# see other postprocessors of version 0.20.1
#
#from PathScripts import PostUtils
#from PathScripts import PathUtils

import PathScripts.PostUtils as PostUtils
import PathScripts.PathUtils as PathUtils
# sjj, 2023-01-02, end
```

Unfortunately without success
The gcode generation stops with this error:

```
15:02:30  snapmaker_freecad_post gcode postprocessor loaded.
15:02:40  snapmaker_freecad_post gcode postprocessor loaded.
15:02:43  snapmaker_freecad_post gcode postprocessor loaded.
15:02:43  <Path.Area> Area.cpp(2691): edge break point not found
15:02:43  <Path.Area> Area.cpp(2691): edge break point not found
15:02:43  <Path.Area> Area.cpp(2691): edge break point not found
15:02:43  <Path.Area> Area.cpp(2691): edge break point not found
15:02:43  <Path.Area> Area.cpp(2691): edge break point not found
15:02:43  <Path.Area> Area.cpp(2691): edge break point not found
15:02:43  helix_generator(59).generate((helix: <0.0, -56.0>
 hole radius 5.2
 inner radius 0.0
 step over 0.5
 start point 0.0
 end point -5.1
 step_down 6.0
 tool diameter 6.0
 direction CW
 startAt Inside))
15:02:43  helix_generator.DEBUG: (124) - (single helix mode)

15:02:43  helix_generator.DEBUG: (144) - Radii: [2.2]
15:02:43  helix_generator(59).generate((helix: <0.0, -56.0>
 hole radius 5.2
 inner radius 0.0
 step over 0.5
 start point 0.0
 end point -5.1
 step_down 6.0
 tool diameter 6.0
 direction CW
 startAt Inside))
15:02:43  helix_generator.DEBUG: (124) - (single helix mode)

15:02:43  helix_generator.DEBUG: (144) - Radii: [2.2]
15:02:46  post: snapmaker_freecad(D:/OneDrives/OneDrive - La Gondola Barocca/_PCBüroLustheim/Eigene Dateien/CAD, Designer, Publisher/_CNC-Fräsungen/Vakuumplatte/vakuumplatte200x200.snapmaker.cnc, )
15:02:46  snapmaker_freecad_post gcode postprocessor loaded.
15:02:46  Show editor = 1
15:02:46  postprocessing...
15:02:46  Running the Python command 'Path_Post' failed:
Traceback (most recent call last):
  File "C:\Program Files\FreeCAD\0.20.1.stable\Mod\Path\PathScripts\PathPost.py", line 437, in Activated
    (fail, rc, filename) = self.exportObjectsWith(slist, job)
  File "C:\Program Files\FreeCAD\0.20.1.stable\Mod\Path\PathScripts\PathPost.py", line 216, in exportObjectsWith
    gcode = processor.export(objs, filename, postArgs)
  File "C:\Program Files\FreeCAD\0.20.1.stable\Mod\Path\PathScripts\PathPostProcessor.py", line 105, in export
    return self.script.export(obj, filename, args)
  File "C:\Program Files/FreeCAD/0.20.1.stable/Mod/Path/PathScripts/post\snapmaker_freecad_post.py", line 204, in export
    job = PathUtils.findParentJob(obj)
  File "C:\Program Files\FreeCAD\0.20.1.stable\Mod\Path\PathScripts\PathUtils.py", line 405, in findParentJob
    for i in obj.InList:

'_TempObject' object has no attribute 'InList'
```

Another google search for the error text at the end didn't get me anywhere.

Thank you for your help.

Many greetings

Sepp

**Comment by spitzlbergerj** [comment]
Hi, 
after not being able to isolate or even solve the bug further, I no longer use Snapmaker's postprocessor published here. No one seems to care about this issue either. 
I found what I was looking for on [github ](https://github.com/clsergent/Snapmaker2Postprocessor) with @clsergent. He has developed a postprocessor that works great and for which he provides excellent support. 
This for all who are looking for something similar 
Greetings 
Sepp
